services:
  # Servicio para ejecutar tests del core
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: backgammon-test
    volumes:
      - .:/app
    command: python -m unittest discover -s backgammon/tests -p test_*.py

  # Servicio para ejecutar tests con coverage
  coverage:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: backgammon-coverage
    volumes:
      - .:/app
    command: sh -c "coverage run -m unittest discover -s backgammon/tests -p test_*.py && coverage report -m"

  # Servicio para ejecutar pylint solo en core
  lint:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: backgammon-lint
    volumes:
      - .:/app
    command: pylint backgammon/core/