FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt && \
    pip install --no-cache-dir coverage pylint

COPY backgammon ./backgammon

COPY .pylintrc* ./

CMD ["python", "-m", "unittest", "discover", "-s", "backgammon/tests", "-p", "test_*.py"]