name: CI with Coverage and SonarCloud
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint

      - name: Install ansi2txt for clean reports
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends moreutils
        shell: bash

      - name: Run tests and generate coverage report
        run: |
          # El comando de cobertura usa el archivo .coveragerc
          coverage run -m unittest discover
          coverage xml -o cobertura.xml
          coverage report -m > coverage_report.txt

      - name: Run Pylint and generate text report
        run: |
          # 1. Ejecutar Pylint, canalizando la salida directamente al archivo (limpio de colores)
          pylint backgammon --rcfile=.pylintrc -f colorized | ansi2txt > pylint_output.txt
          
          # 2. Mover el contenido real al archivo de texto para el reporte.
          cat pylint_output.txt > pylint_report.txt

          # 3. CRUCIAL: Generar el reporte XML. Usamos '|| true' para asegurar que el archivo de salida se cree 
          #    incluso si Pylint falla y retorna un código de error (siempre y cuando la opción continue-on-error esté en su sitio).
          pylint backgammon --rcfile=.pylintrc --output-format=pylintxml > pylint.xml || true 
          
        continue-on-error: true

      - name: Generate reports file
        run: |
          cat << 'EOF' > generate_reports.py
          import os
          def read_file(filepath):
              if not os.path.exists(filepath):
                  # Retorna un mensaje de error si el reporte no existe
                  return f"File not generated at {filepath}"
              try:
                  with open(filepath, "r", encoding="utf-8") as f:
                      return f.read()
              except Exception as e:
                  return f"Error reading file {filepath}: {e}"
                  
          coverage_report = read_file("coverage_report.txt")
          pylint_report = read_file("pylint_report.txt")

          reports_content = f"""# Automated Reports
          
          ## CI Status
          **Commit:** ${{ github.sha }}
          
          ## Coverage Report
          ```text
          {coverage_report}
          ```
          
          ## Pylint Report
          ```text
          {pylint_report}
          ```
          """
          with open("REPORTS.md", "w", encoding="utf-8") as f:
              f.write(reports_content)
          EOF
          python generate_reports.py

      - name: Commit and Push Reports
        if: always() # Ejecutar siempre, incluso si los tests fallan
        run: |
          git config --global user.name 'GitHub Actions Report'
          git config --global user.email 'github-actions@github.com'
          git checkout ${{ github.head_ref }} || git checkout ${{ github.ref }} # Vuelve a la rama original
          
          git add REPORTS.md cobertura.xml
          git commit -m "docs: Update Automated CI Reports [skip ci]" || echo "No changes to commit"