name: CI with Coverage and SonarCloud
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint

      - name: Install ansi2txt for clean reports
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends moreutils
        shell: bash

      - name: Run tests and generate coverage report
        run: |
          coverage run -m unittest discover
          coverage xml -o cobertura.xml
          coverage report -m > coverage_report.txt

      - name: Run Pylint and generate text report
        run: |
          # Generar el reporte de texto estándar (eliminando la dependencia de ansi2txt para esta salida)
          pylint backgammon --rcfile=.pylintrc -f text > pylint_report.txt

          # Generar el reporte XML (necesario para SonarCloud/CodeClimate, aunque no se vea en el .md)
          pylint backgammon --rcfile=.pylintrc --output-format=pylintxml > pylint.xml || true 
        
        continue-on-error: true

      - name: Generate reports file
        run: |
          cat << 'EOF' > generate_reports.py
          import os
          def read_file(filepath):
              if not os.path.exists(filepath):
                  return f"File not generated at {filepath}"
              try:
                  with open(filepath, "r", encoding="utf-8") as f:
                      return f.read()
              except Exception as e:
                  return f"Error reading file {filepath}: {e}"
                  
          coverage_report = read_file("coverage_report.txt")
          pylint_report = read_file("pylint_report.txt")
          reports_content = f"""# Automated Reports
          
          ## CI Status
          **Commit:** ${{ github.sha }}
          
          ## Coverage Report
          ```text
          {coverage_report}
          ```
          
          ## Pylint Report
          ```text
          {pylint_report}
          ```
          """
          with open("REPORTS.md", "w", encoding="utf-8") as f:
              f.write(reports_content)
          EOF
          python generate_reports.py

      - name: Create Pull Request for reports
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'docs: Update Automated CI Reports [skip ci]'
          title: 'Automated Reports Update'
          body: |
            ## Automated Reports Update
            This PR contains the latest automated reports:
            - Coverage Report
            - Pylint Report
            Generated by GitHub Actions workflow.
          branch: automated-reports-update
          delete-branch: true
          add-paths: |
            REPORTS.md
            cobertura.xml
            pylint.xml